version: '3'

services:
  api-dotnet:
    image: crud-dotnet
    build: ./Backend/
    restart: unless-stopped
    depends_on: 
      - sql-server
    volumes:
      - ./config/appsettings.json:/app/appsettings.json
    networks:
      - my-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: SecurePassword#123
      MSSQL_PID: Express
    ports:
      - 7654:1433
    networks:
      - my-network

  front-angular:
    image: angular-nginx
    build: ./Front/
    ports:
      - 80:80
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
